[package]
name = "cannon-rs"
description = "Binary crate for cannon-rs"
edition = "2021"

version.workspace = true
authors.workspace = true

[dependencies]
# External
clap = { version = "4.4.3", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
anyhow = "1.0.75"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
alloy-primitives = "0.3.3"
tokio = { version = "1.32.0", features = ["macros"] }
flate2 = "1.0.27"
async-trait = "0.1.73"

# Local
cannon-mipsevm = { path = "../crates/mipsevm" }
preimage-oracle = { path = "../crates/preimage" }

[dev-dependencies]
proptest = "1.2.0"

[[bin]]
name = "cannon"
path = "src/cannon.rs"
