[package]
name = "cannon-rs"
description = "Binary crate for cannon-rs"
edition = "2021"

version.workspace = true
authors.workspace = true

[dependencies]
# External
anyhow = "1.0.75"
clap = { version = "4.4.3", features = ["derive"] }
alloy-primitives = "0.4.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"

# Local
cannon = { path = "../crates/cannon" }
cannon-mipsevm = { path = "../crates/mipsevm" }

[[bin]]
name = "cannon"
path = "src/cannon.rs"
