[package]
name = "cannon-mipsevm"
description = "An implementation of the MIPSEVM for Cannon"
edition = "2021"

version.workspace = true
authors.workspace = true

[dependencies]
alloy-primitives = "0.3.3"
once_cell = "1.18.0"
serde = "1.0.188"
serde_json = "1.0.106"

anyhow = "1.0.70"
tracing = "0.1.37"
