[package]
name = "cannon-mipsevm"
description = "An implementation of the MIPSEVM for Cannon"
edition = "2021"

version.workspace = true
authors.workspace = true

[dependencies]
alloy-primitives = "0.3.3"
once_cell = "1.18.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.106"
fnv = "1.0.7"

# misc
anyhow = "1.0.75"
tracing = "0.1.37"

[dev-dependencies]
rand = "0.8.5"
revm = "3.3.0"

[features]
tracing = []
