name: Rust CI
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install xsltproc
        run: sudo apt-get install xsltproc
      - uses: taiki-e/install-action@nextest
      - name: cargo test
        run: cargo nextest run --workspace --all --all-features --locked
  cargo-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install xsltproc
        run: sudo apt-get install xsltproc
      - name: cargo fmt
        run: cargo +nightly fmt --all -- --check
      - name: cargo clippy
        run: cargo +nightly clippy --workspace --all --all-features --locked -- -D warnings
  cargo-build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install xsltproc
        run: sudo apt-get install xsltproc
      - name: build
        id: build
        run: cargo build --workspace --all --locked 
  cargo-doc:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust nightly toolchain
        uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Install xsltproc
        run: sudo apt-get install xsltproc
      - name: doclint
        id: build
        continue-on-error: true
        run: RUSTDOCFLAGS="-D warnings" cargo doc --all --no-deps --all-features --document-private-items
      - name: doctest
        run: cargo test --doc --all --all-features --locked

